version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'kraken-database'
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'
  server:
    build: .
    container_name: 'kraken-server'
    command: npm start
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    links:
      - mongodb
